version: '3.6'
services:
  wallet:
    container_name: wallet
    image: shroomlife/reddcoin-docker-wallet:latest
    restart: always
    volumes:
      - "blockchain:/root/.reddcoin"
    environment:
      - "CMC_API_KEY=<YOUR COINMARKETCAP API KEY>"
volumes:
  blockchain:
